config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  get 'catalog' => 'pages_controller#catalog'
  get 'delivery' => 'pages_controller#delivery'
  get 'contact' => 'pages_controller#contact'
  root 'products#index'
  devise_for :customers, controllers: {
    regisrations: 'regisrations'
  }

  devise_scope :customer do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)

    if current_item
      current_item.increment(:quantity)
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Ваша корзина была удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
    def invalid_cart
     logger.error " Порытка зайти в неправльную карту#{params[:id]}"
     redirect_to root_path, notice: "Карточка не существует"
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= simple_form_for(@cart) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<main>
  <nav class=" d-flex justify-content-center my-4">

    <div><h4>Корзина</h4></div>
  </nav>
  <div class="m-4">

    <div class="card">

      <div class="card-body">
        <table class="table table-hover text-center">
          <thead class="table-borderless">
            <tr>
              <th scope="col" class="table-item-line"></th>
              <th scope="col">Количество</th>
              <th scope="col">Цена</th>
            </tr>
          </thead>
          <tbody>
            <%= render(@cart.line_items) %>
          </tbody>
        </table>
      </div>

      <div class="card-footer bg-transparent cart-footer">
        <%= button_to 'Продолжить покупки', products_path, class: 'btn btn-xs text-muted my-3 btn-as-link' %>
        <%= button_to 'Очистить корзину', @cart, method: :delete, data: { confirm: "Вы уверены? " }, class: "btn btn-xs text-muted my-3 btn-as-link" %>
        <button class="btn btn-mint float-right mx-4 my-3 btn-order">Оформить заказ</button>
        <div class="float-right my-4"><span class="mr-2">Сумма заказа:</span><span class="mr-3"><%= number_to_currency(@cart.total_price,:locale => :ru) %></span></div>
      </div>
    </div>

  </div>
</main>