config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  get 'catalog' => 'pages_controller#catalog'
  get 'delivery' => 'pages_controller#delivery'
  get 'contact' => 'pages_controller#contact'
  root 'products#index'
  devise_for :customers, controllers: {
    regisrations: 'regisrations'
  }

  devise_scope :customer do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_line_item
  mount_uploader :image, ImageUploader
  serialize :image, JSON
  belongs_to :customer, optional: true
  has_many :line_items

  COUNTRY = %w{Китай Россия Индия Шриланка Япония}
  KIND_TEA = %w{ Рассыпной Прессованный}
  SORT_TEA = %w{Красный Зеленый Белый Улун Пуэр Желтый}

  private

  def not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, "Текущий итем")
      throw :abort

    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_customer!, except: [:index, :show]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all.order("created_at desc")
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_customer.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_customer.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :small_description, :price, :country, :kind_tea, :sort_tea, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper

def product_author(product)
    customer_signed_in? && current_customer.id == product.customer_id
end

end

app/views/products/_form.html.erb
<main>
  <div class="d-flex justify-content-center m-5">

    <%= simple_form_for @product, html: { multipart: true } do |f| %>

        <form class="data-edit-form">
          <h5 class="mb-3">Добавление нового товара</h5>
          <hr class="mb-4">

          <div class="form-group row form-inline">
                <%= f.input :title, input_html: { class: "form-control"}, wrapper: false, label_html: { class:"col-sm-4 col-form-label" }, label: "Название"%>
          </div>

          <div class="form-group row form-inline">
              <%= f.input :price, input_html: { class:"col-sm-8, form-control", maxlength: 7  }, wrapper: false, label_html: { class:"col-sm-4 col-form-label"}, label: "Цена"  %>
          </div>


          <div class="form-group row form-inline">
            <label class="col-sm-4 col-form-label" for="inputDiscription">Описание</label>
            <div class="col-sm-8">
            <%= f.input :description, as: :text, input_html: {class:" form-control"}, label: false %>
            </div>
          </div>


          <div class="form-group row form-inline">
            <%= f.input :small_description, input_html:{class:"form-control"}, wrapper: false, label_html: { class:"col-sm-4 col-form-label"}, label: "Перевод"  %>
          </div>

          <div class="form-group row form-inline">
            <label for="inputCountry" class="col-sm-4 col-form-label">Страна</label>
            <%= f.input_field :country, class:"form-control form-control-sm", collection: Product::COUNTRY, prompt: "Выберите страну"%>
          </div>

          <div class="form-group row form-inline">
            <label for="inputPacking" class="col-sm-4 col-form-label">Вид фасовки</label>
            <%= f.input_field :kind_tea,  collection: Product::KIND_TEA, prompt: "Выберите вид фасовки", class:'form-control form-control-sm'%>
          </div>

          <div class="form-group row form-inline">
            <label for="inputSortTea" class="col-sm-4 col-form-label">Сорт чая</label>
             <%= f.input_field :sort_tea, class:"form-control form-control-sm", collection: Product::SORT_TEA, prompt: "Выберите сорт" %>
          </div>

          <div class="form-group row form-inline">
            <label for="File1" class="col-sm-4 col-form-label">Добавить изображение</label>
            <div class="col-sm-8">
              <%= f.input :image, as: :file, class:"form-control-file" , label: false, wrapper: false %>
            </div>
          </div>

          <hr class="mb-4 mt-5">
          <div class="form-group row">
            <div class="col-sm-8 ml-3">
              <%= f.button :submit, 'Добавить товар', class: 'btn btn-mint btn-lg' %>
            </div>
          </div>
        </form>
      </div>
      <% end %>
</main>

app/views/products/edit.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Редактирование карточки продукта
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<!-- CAROUSEL -->
<div id="banner" class="carousel slide carousel-fade" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#banner" data-slide-to="0" class="active"></li>
    <li data-target="#banner" data-slide-to="1"></li>
    <li data-target="#banner" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("banner1.png", class: "d-block w-100")%>
    </div>
    <div class="carousel-item">
      <%= image_tag("carousel2.jpeg", class: "d-block w-100")%>
    </div>
    <div class="carousel-item">
      <%= image_tag("carousel3.jpg", class: "d-block w-100")%>
    </div>
  </div>
  <a class="carousel-control-prev" href="#banner" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#banner" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<!-- MAIN -->
<div class="d-flex flex-column h-100">
  <main role="main" class="flex-shrink-0">
    <div class="container">
      <h1 class="mt-4">Горячее</h1>
      <p class="underhead mb-4">Самые выгодные предложения</p>

      <div class="d-flex flex-row flex-wrap justify-content-start">

        <!-- Card -->
        <% @products.each do |product| %>
        <div class="card mx-3">
          <div class="hover ehover1">
            <%= link_to image_tag(product.image_url(:thumb)), product, class:"img-responsive card-img-top" %>
            <div class="overlay d-flex flex-column">
              <div class="in-fav"><a href="#" class="float-right badge">В избранное</a></div>
              <div class="eye"><i><%= link_to '', product_path(product), class: "fas fa-eye"%></i>
               <br> <%= link_to 'Подробнее', product_path(product), class: "font-eye"%></div>

            </div>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= link_to product.title, product, class:"" %></h5>
            <p class="card-text"><%=product.small_description%></p>
            <div class="container-fluid align-items-center">

              <a href="#" class="tag badge badge-pill white-tea">Белый</a>
              <a href="#" class="tag badge badge-pill discount">-30%</a>
              <p class="float-right wt">50г</p>
            </div>
            <div><hr class="featurette-divider"></div>

            <div class="container-fluid">
              <span class="card-text price"><%= number_to_currency(product.price,:locale => :ru) %></span>
              <%= button_to 'В корзину', line_items_path(product_id: product), class: 'in-cart btn float-right' %>
            </div>
          </div>
        </div>
        <% end %>
      </div>


      <div class="button d-flex justify-content-center">
        <%= link_to 'Перейти в каталог', catalog_url, class: "badge" %>
      </div>
      <hr class="featurette-divider">

      <div class="container main-block">
        <h1 class="my-4">О компании</h1>
        <p class="underhead about-us mb-4">У нас вы можете купить китайский чай в Архангельске или заказать его с доставкой в регионы России. Магазин TeaStore образовался в результате многолетнего увлечения чаем и его культурой. Наша цель — делать хороший китайский чай доступным, тем самым способствуя его распространению. Каждый год в течении трёх месяцчев мы проезжаем весь Китай в поисках чая и подбора ассортимента. Отсутствие цепочки посредников, отработанная логистика в Россию, знание рынка, умение подбирать чай, оптимизация арендных площадей и рабочего пространства в Москве, автоматизация внутренних процессов, создание условий хранения – всё это даёт возможность предлагать вам лучшую цену на китайский чай высочайшего качества.</p>


      </div>
    </div>
  </div>
</main>
</div>

app/views/products/new.html.erb
<% content_for :header do %>
<section class="hero is-warning">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Карточка продажи чая
      </h1>
    </div>
  </div>
</section>
<% end %>

<div class="pv4">
  <%= render 'form', product: @product %>
</div>

app/views/products/show.html.erb
  <main>
      <div class="container d-flex px-5 pt-5">
        <div class="my-5 mr-5">
          <%= link_to image_tag(@product.image_url(:default)), @product, class:"product-img" %>
          <div>
            <small>
              <a class="sys-btn pr-2"><%= link_to 'Редактировать', edit_product_path(@product), class: "sys-btn pr-2" %></a>
              <a class="sys-btn"><%= link_to 'Удалить', @product, method: :delete, data: { confirm: "Are you sure ?" }, class: "sys-btn" %></a>
            </small>
          </div>
        </div>
        <div class="m-5 container-costil-shirina">
          <h3> <%= @product.title %></h3>
          <p class="underhead-product-title"><%= @product.small_description%></p>
          <hr>
          <div class="d-flex">
            <a href="#" class="tag badge badge-pill green-tea tag-product">Зеленый</a>
            <a href="#" class="tag badge badge-pill year-tea tag-product">2018</a>
            <a href="#" class="tag badge badge-pill country-tea tag-product">Китай</a>
            <a href="#" class="tag badge badge-pill packing-tea tag-product">Рассыпной</a>
          </div>
          <p class="mt-4"><%= @product.small_description%></p>
          <div class="d-flex">
            <p class="mr-3">Фасовка:</p>
            <div class=" btn-group-toggle button" data-toggle="buttons">
              <label class="btn btn-secondary active">
                <input type="radio" name="options" id="option1" autocomplete="off" checked> 7г
              </label>
              <label class="btn btn-secondary">
                <input type="radio" name="options" id="option2" autocomplete="off"> 25г
              </label>
              <label class="btn btn-secondary">
                <input type="radio" name="options" id="option3" autocomplete="off"> 50г
              </label>
              <label class="btn btn-secondary">
                <input type="radio" name="options" id="option3" autocomplete="off"> 100г
              </label>
            </div>
          </div>

          <hr class="mt-5 hr-width">
          <div class="d-flex justify-content-between">
            <div class="d-flex">
              <h5 class="mr-3">Цена:</h5>
              <h5><%= number_to_currency(@product.price,:locale => :ru) %></h5>
            </div>
            <div>
              <%= button_to 'Добавить в корзину', line_items_path(product_id: @product), class: 'btn btn-bay mr-4' %>
            </div>
          </div>

        </div>

      </div>

      <hr class="featurette-divider">
      <div class="container px-5 py-3 descript-p">
        <h4>Вкус, цвет и аромат:</h4>
        <p>Насыщенный аромат орхидей. Здесь также угадываются легкие шоколадные ноты, которые в сочетании с цветами дают сложный глубокий аромат. Вкус напитка — насыщенный, маслянистый, с освежающим послевкусием.
        В Китае говорят: при первой заварке он дает яркий аромат, при второй — насыщенный вкус, при третьей — гармонию.</p>
        <h4>Как заваривать:</h4>
        <%= image_tag("zavar.jpg", :alt => "Способ заваривания", class: "mb-3") %>
        <p>Выбирайте мягкую, качественную воду для заваривания.
        Заваривайте чай проливами. Этот зеленый чай выдерживает до 8 проливов без потери вкуса.</p>
        <h4>Почему стоит купить:</h4>
        <p>Общеукрепляющий, тонизирующий чай, регулирует обмен веществ, расширяет сосуды и укрепляет их стенки, снижает холестерин, нормализует давление, стимулирует пищеварение, хорошо освежает. Китайцы считают, что он избавляет от чувства усталости.
        Чай Тай пин Хоу Куй купить и не прогадать с качеством не просто. Мы гарантируем прямые поставки из Китая и наш чай всегда свежий! Доставим вашу покупку по Москве курьером или почтой по всей России.</p>

      </div>

  </main>