config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  resources :products
  get 'catalog' => 'pages_controller#catalog'
  get 'delivery' => 'pages_controller#delivery'
  get 'contact' => 'pages_controller#contact'
  root 'products#index'
  devise_for :customers, controllers: {
    regisrations: 'regisrations'
  }

  devise_scope :customer do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TeaStory</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="http://bootstraptema.ru/snippets/effect/2016/ihe/effects.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

</head>
<body class="d-flex flex-column">

 <!-- TOP BAR -->
 <div class="container-fluid top-bar ">
  <div class="row justify-content-between align-items-center border-bottom px-4 py-1">
    <div class="col-sm-6"><i class="fas fa-map-marker-alt"></i> Доставка по Архангельску</div>
    <div class="col-sm-6">
      <span class="float-md-right"><i class="fas fa-phone"></i> 8 (926) 049 90 79 &nbsp;&nbsp;&nbsp;&nbsp;<a href="#">Избранное</a></span>
    </div>
  </div>
</div>

<!-- NAVBAR -->
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top border-bottom">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse flex-lg-fill pl-3" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          КАТАЛОГ
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to 'Чай', catalog_url, class: "dropdown-item" %>
          <a class="dropdown-item" href="#">Посуда</a>
          <a class="dropdown-item" href="#">Аксессуары</a>
        </div>
      </li>
      <li class="nav-item pl-2">
        <a class="nav-link" href="#">БЛОГ</a>
      </li>
      <li class="nav-item pl-2">
        <%= link_to 'ДОСТАВКА', delivery_url, class: "nav-link" %>
      </li>
      <li class="nav-item pl-2">
        <%= link_to 'КОНТАКТЫ', contact_url, class: "nav-link" %>
      </li>
      <li class="nav-item pl-2">
        <a class="nav-link" href="#">АКЦИИ</a>
      </li>
    </ul>
  </div>

  <%= link_to root_path, :class => "navbar-brand flex-lg-fill" do %>
  <%= image_tag("logo.png", :alt => "Логотип", class: "h-38") %>
  <% end %>

  <div class="collapse navbar-collapse justify-content-md-end flex-lg-fill px-3 " id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item pr-2">
        <!-- TODO: сделать выпадающий поиск jquery -->
        <a class="nav-link " href="#"><i class="fas fa-search"></i></a>
      </li>
      <li class="nav-item pr-3">
        <%= link_to '', @cart, class: "nav-link fas fa-shopping-cart" %>
      </li>
      <% if customer_signed_in? %>
      <li class="nav-item">
        <%= link_to 'Добавить товар', new_product_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to current_customer.email, edit_customer_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item ">
       <%= link_to "Выйти", destroy_customer_session_path, method: :delete, class:"nav-link" %>
     </li>
     <% else %>
     <li class="nav-item">
      <%= link_to "Вход", new_customer_session_path, class:"nav-link" %>
    </li>
    <li class="nav-item ">
      <%= link_to "Регистрация", new_customer_registration_path, class:"nav-link"%>
    </li>
    <% end %>
  </ul>
</div>
</nav>


<%= yield %>

<!-- FOOTER -->
<footer class="footer mt-auto py-3 border-top ">
  <div class="container">
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <a class="nav-link slash" href="#">ДОСТАВКА И ОПЛАТА</a>
      </li>
      <li class="nav-item">
        <a class="nav-link slash" href="#">БЛОГ</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">СПОСОБЫ ЗАВАРИВАНИЯ</a>
      </li>
    </ul>
  </div>
  <div class="d-flex justify-content-center">
    <a class="nav-link" href="https://vk.com/tea_story29"><i class="fab fa-vk"></i> </a>
    <a class="nav-link" href="https://www.instagram.com/tea_story29/"><i class="fab fa-instagram px-4"></i></a>
  </div>
  <div class="d-flex justify-content-center">
    <span class="text-muted pr-4">8 (926) 049 90 79</span>
    <span class="text-muted pl-3">teastory@gmail.com</span>
  </div>
</footer>

</body>
</html>